version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /mnt/data:/mnt/data
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
